/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniyuan_MainActivity */

#ifndef _Included_com_example_jniyuan_MainActivity
#define _Included_com_example_jniyuan_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniyuan_MainActivity
 * Method:    setMi
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniyuan_MainActivity_setMi
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_jniyuan_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jniyuan_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_jniyuan_MainActivity
 * Method:    asd
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_jniyuan_MainActivity_asd
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
