/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cdyjava_MainActivity */

#ifndef _Included_com_example_cdyjava_MainActivity
#define _Included_com_example_cdyjava_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cdyjava_MainActivity
 * Method:    setCToJava
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_cdyjava_MainActivity_setCToJava
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
